name: warnings
description: "A base project to support the development of the Warning Apps"
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 0.0.4

environment:
  sdk: '^3.8.0'

dependencies:
  flutter:
    sdk: flutter

  dart_mappable: ^4.2.2
  firebase_core: ^4.0.0
  firebase_messaging: ^16.0.0
  fl_chart: ^1.0.0
  flex_color_scheme: ^8.2.0
  flutter_bloc: ^9.1.1
  flutter_local_notifications: ^19.4.0
  flutter_map: ^8.2.1
  flutter_svg: ^2.0.10+1
  fogos_api: 0.0.6
  get_it: ^8.1.0
  go_router: ^16.0.0
  intl: any
  latlong2: ^0.9.1
  sentry: ^9.5.0
  wolt_modal_sheet: ^0.11.0
  warnings_core:
  svg_flutter:
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  build_runner: ^2.4.15
  json_serializable: ^6.9.1
  dart_mappable_builder: ^4.2.3

flutter:
  generate: true
  uses-material-design: true
