name: fogos
repository: https://github.com/FogosPT/fogospt.git 

packages:
  - apps/*
  - packages/*

ide:
  intellij:
    enabled: false

command:
  bootstrap:
    environment:
      sdk: '^3.8.0'
      flutter: '>=2.17.0 <3.0.0'

    dependencies:
      equatable: ^2.0.2
      flutter_bloc: ^8.1.6
      flutter_map: ^8.2.1
      freezed: ^2.4.7
      get_it: ^7.7.0
      http: ^1.2.1
      latlong2: ^0.9.1
      mason: ^0.1.0-dev.57
      sentry_flutter: ^8.8.0
      sentry: ^8.8.0

    dev_dependencies:
      bloc_test: ^9.1.6
      build_runner: ^2.1.2
      flutter_lints: ^3.0.1
      json_serializable: ^6.7.1
      mockito: ^5.4.4

    # hooks:
    #   post: dart pub run build_runner build
      
  version:
    branch: vega


scripts: 
  analyze:
    exec: dart analyze .
  # fix:
  #   exec: dart fix . && dcm fix .

  build:
    exec: dart run build_runner build
    description: Run build runner on the projects 
    packageFilters:
      dependsOn: build_runner

  buildAll:
    exec: dart run build_runner build --delete-conflicting-outputs
    description: Run build runner on the projects and delete all dependencies
    packageFilters:
      dependsOn: build_runner
  
  get: 
    exec: dart pub get
    description: Get the dependencies
    packageFilters:
      dependsOn: flutter

  l10n:
    exec: dart pub get && flutter gen-l10n
    description: Generate localization files
    packageFilters:
      dependsOn: flutter
      dirExists: lib/l10n

  l10n-untranslated:
    exec: dart pub get && flutter gen-l10n --no-update-arb-files --no-update-translations
    description: Generate localization files
    packageFilters:
      dependsOn: flutter
      dirExists: lib/l10n