name: fogosmobile
description: Fogos.pt new iOS and Android app

version: 5.0.1+500010

environment:
  sdk: '^3.8.0'

dependencies:
  dart_mappable: ^4.2.2
  firebase_messaging: ^15.0.3
  flutter:
    sdk: flutter
  flutter_local_notifications: ^19.4.0
  flutter_localizations:
    sdk: flutter
  intl: any
  mason: ^0.1.0-dev.57
  sentry_flutter: ^8.8.0

dev_dependencies:
  build_runner: ^2.4.15
  dart_mappable_builder: ^4.2.3
  flutter_test:
    sdk: flutter
  melos: ^6.0.0

flutter:
  generate: true
  uses-material-design: true

  fonts:
    - family: Urbanist
      fonts:
        - asset: assets/fonts/urbanist/Urbanist-Italic-VariableFont.ttf
        - asset: assets/fonts/urbanist/Urbanist-VariableFont.ttf
    - family: Londrina
      fonts:
        - asset: assets/fonts/londrina/LondrinaSolid-Black.ttf
        - asset: assets/fonts/londrina/LondrinaSolid-Light.ttf
        - asset: assets/fonts/londrina/LondrinaSolid-Regular.ttf
        - asset: assets/fonts/londrina/LondrinaSolid-Thin.ttf