# This is a Taskfile, a simple way to define tasks for your projects.
# For more information, check out https://taskfile.dev/#/usage
version: '3'

tasks:
  clean:
    cmds:
      - echo "Cleaning up..."
      - flutter clean
      - echo "Fetching dependencies..."
      - flutter pub get
      - echo "Done"
  nuke:
    cmds:
      - echo "Nuking..."
      - echo "Cleaning git through untracked directories, forced enabled to delete all untracked files, and build files..."
      - git clean -dfx 
      - echo "Cleaning global Dart cache..."
      - dart pub cache clean
      - echo "Cleaning up Flutter files..."
      - flutter clean
      - echo "Fetching dependencies..."
      - flutter pub get
      - echo "Flutter analyze..."
      - flutter analyze
      - echo "Dart analyze..."
      - dart analyze
      - echo "Done"


