name: fogospt
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.3

environment:
  sdk: '^3.3.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6

  go_router: ^13.2.0

  logger: ^2.0.2+1
  equatable: ^2.0.2
  freezed: ^2.4.7
  sentry: ^7.18.0

  fogos_api: 0.0.1+2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:

  uses-material-design: true