name: fogos_api
description: "A new Flutter package project."
version: 0.0.1+1
publish_to: none

environment:
  sdk: ^3.3.0

dependencies:
  flutter:
    sdk: flutter
  warnings_api: 
    path: ../warnings_api
  


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter: