#!/bin/sh
# This is a generated file; do not edit or check into version control.
export "FLUTTER_ROOT=/Users/guilherme/dev/tools/flutter"
export "FLUTTER_APPLICATION_PATH=/Users/guilherme/dev/fogos2/fogosmobile"
export "FLUTTER_TARGET=/Users/guilherme/dev/fogos2/fogosmobile/lib/main.dart"
export "FLUTTER_BUILD_DIR=build"
export "SYMROOT=${SOURCE_ROOT}/../build/ios"
export "OTHER_LDFLAGS=$(inherited) -framework Flutter"
export "FLUTTER_FRAMEWORK_DIR=/Users/guilherme/dev/tools/flutter/bin/cache/artifacts/engine/ios"
export "FLUTTER_BUILD_NAME=4.0.0"
export "FLUTTER_BUILD_NUMBER=40000"
export "DART_DEFINES=flutter.inspector.structuredErrors%3Dtrue"
export "DART_OBFUSCATION=false"
export "TRACK_WIDGET_CREATION=true"
export "TREE_SHAKE_ICONS=false"
